package com.example.haboob;

import android.os.Bundle;

import com.example.haboob.ui.home.EntrantMainFragment;
import com.example.haboob.ui.home.myCallback;
import com.google.android.material.bottomnavigation.BottomNavigationView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.navigation.NavController;
import androidx.navigation.Navigation;
import androidx.navigation.ui.AppBarConfiguration;
import androidx.navigation.ui.NavigationUI;

import com.example.haboob.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {

    // gives us access to the views in the layout generated by activity_main.xml
    private ActivityMainBinding binding;

    // create an EventsList that we can pass to all our fragments:
    private EventsList eventsList;


    // create a method that returns our EventsList:
    public EventsList getEventsList() {
        return eventsList;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // 1) Make the eventsList ready BEFORE inflating layout (which creates the fragment)
        eventsList = new EventsList(/* maybe getApplicationContext() if needed */);

        // Creates the binding object by inflating activity_main.xml
        binding = ActivityMainBinding.inflate(getLayoutInflater());

        // Sets the activity’s content to the root view of that inflated layout. From this point on, the activity is showing activity_main.xml.
        setContentView(binding.getRoot());

        // Gets a reference to your bottom nav bar defined in activity_main.xml
        BottomNavigationView navView = findViewById(R.id.nav_view);

        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.
        // Put here the fragment IDs that map to bottom-nav tabs.
        AppBarConfiguration appBarConfiguration = new AppBarConfiguration.Builder(
                R.id.navigation_home, R.id.navigation_dashboard, R.id.navigation_notifications)
                .build();
        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment_activity_main);
//        NavigationUI.setupActionBarWithNavController(this, navController, appBarConfiguration);
        NavigationUI.setupWithNavController(binding.navView, navController);
    }

}